Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import random
random.choice(['rock','paper','scissor'])
'paper'

============================================================= RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/game.py =============================================================
enter rock/paper/scissor:rock
Traceback (most recent call last):
  File "C:/Users/Ramesh/Desktop/internship/17-02-23/game.py", line 5, in <module>
    if player == cpu:
NameError: name 'player' is not defined. Did you mean: 'player1'?

============================================================= RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/game.py =============================================================
enter rock/paper/scissor:scissor
cpu rocks player1 shocks

====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
Traceback (most recent call last):
  File "C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py", line 5, in <module>
    server.login('kpathivada@gmail.com','fhtihhjtflxgbaqh')
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ju10-20020a170903428a00b0019b4ee071dfsm674182plb.213 - gsmtp')



====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
Traceback (most recent call last):
  File "C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py", line 5, in <module>
    server.login('kpathivada@gmail.com','fhtihhjtflxgbaqh')
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x18-20020aa784d2000000b005a8ab25ab0csm2220830pfn.87 - gsmtp')
>>> 
====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
Traceback (most recent call last):
  File "C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py", line 5, in <module>
    server.login('kpathivada@gmail.com','fhtihhjtflxgbaqh')
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials rj3-20020a17090b3e8300b002262dd8a39bsm4176912pjb.49 - gsmtp')
>>> 
====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
Traceback (most recent call last):
  File "C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py", line 5, in <module>
    server.login('kpathivada@gmail.com','fhtihhjtflxgbaqh')
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\Ramesh\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e2-20020a656482000000b004d4547cc0f7sm670899pgv.18 - gsmtp')
>>> 
====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
mail sent
>>> 
====================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating password.py =====================================================
mail sent
>>> 
======================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating otp.py ========================================================
enter to mail kalyanipathivada09@gmail.com
mail sent
enter otp943769
invalid otp-check your eyesight
>>> 
======================================================== RESTART: C:/Users/Ramesh/Desktop/internship/17-02-23/generating otp.py ========================================================
enter to mailkalyanipathivada09@gmail.com
mail sent
enter otp7687
the otp is valid
